apiVersion: v1
kind: Service
metadata:
  labels:
    app: first-microservice
  name: first-service
spec:
  ports:
    - port: 8100
      targetPort: 8100
  selector:
    app: first-microservice
  type: LoadBalancer
  loadBalancerClass: metallb